### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Mila432** [pkmngodev/Unknown6#60]
https://github.com/pkmngodev/Unknown6/wiki
Somebody finally remove the original iPa file ?

https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/d642s4q

**Comment by xssc** [comment]
Why did someone buy an IPA?

**Comment by firebolt55439** [comment]
@xssc He means that whoever downloaded the game using their Apple ID and uploaded it forgot to change the iTunes metadata that has their username. As such, reposting it in the wiki might allow Niantic to identify that person and take retribution against them, which is why @Mila432 is asking us to take it down.

**Comment by Mila432** [comment]
It's not even cracked , so you can't use the bin.

**Comment by keyphact** [comment]
@Mila432 , Hi.

Thanks for catching this, in future would be best if you contact us via more discreet methods.
We're all available on discord.

**Comment by Mila432** [comment]
@keyphact not my file .. My file is decrypted , contains both 32/64 and is id free 
This one http://www.mediafire.com/?dqlho32pgqr6u7d

**Comment by Mila432** [comment]
You can add this link 
https://drive.google.com/open?id=0B5VhBsDM-WN2QkE0bWZIZnpnR0U
